"use client";

import { useEffect, useMemo, useState } from "react";
import { decodeEventLog, formatUnits, parseUnits, type PublicClient } from "viem";
import { useAccount, useChainId, usePublicClient, useReadContract, useSwitchChain, useWriteContract } from "wagmi";
import { baseSepolia } from "wagmi/chains";
import { erc20PaymentAbi, escrowAbi, USTETU_ESCROW_ADDRESS } from "@/lib/contracts";

const BASESCAN_TX = "https://sepolia.basescan.org/tx/";
const PAYMENT_PENDING = 1;
const PAID = 2;
const COMPLETED = 5;
const RPC_TIMEOUT = 4000;
const SCAN_BLOCKS = 100000n;
const MAX_LOG_RANGE = 40000n;
const PENDING_STORAGE = "ustetu.pending-order.v1";

type Step = "idle" | "creating" | "approving" | "funding" | "completing" | "success";
type TxHashes = { create?: `0x${string}`; approve?: `0x${string}`; fund?: `0x${string}`; complete?: `0x${string}` };
type ResumeOrder = { orderId: bigint; tokenAmount: bigint; grossPayment: bigint; state: number; createHash?: `0x${string}` };
type Props = { open:boolean; onClose:()=>void; onCompleted:()=>void; listingId:bigint; symbol:string; price:bigint; available:bigint; minOrderAmount:bigint; maxOrderAmount:bigint; paymentToken:`0x${string}`; tokenDecimals:number; paymentDecimals:number; paymentSymbol:string };

const paymentEscrowedAbi = [{ type:"event", name:"PaymentEscrowed", anonymous:false, inputs:[{indexed:true,name:"orderId",type:"uint256"},{indexed:true,name:"buyer",type:"address"},{indexed:false,name:"amount",type:"uint256"}] }] as const;

const sleep = (ms:number) => new Promise(r => setTimeout(r, ms));
function timeout<T>(p:Promise<T>, ms:number, message:string) { let t:ReturnType<typeof setTimeout>; const x=new Promise<T>((_,rej)=>{t=setTimeout(()=>rej(new Error(message)),ms)}); return Promise.race([p,x]).finally(()=>clearTimeout(t)); }
function key(chainId:number|undefined,buyer:string|undefined,listingId:bigint){return `${PENDING_STORAGE}:${chainId??0}:${buyer?.toLowerCase()??""}:${listingId}`}
function save(k:string,v:unknown){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function load(k:string){try{const x=localStorage.getItem(k);return x?JSON.parse(x):null}catch{return null}}
function clear(k:string){try{localStorage.removeItem(k)}catch{}}
function hashShort(h:`0x${string}`){return `${h.slice(0,8)}…${h.slice(-6)}`}
function errorText(e:unknown){const m=e instanceof Error?e.message:String(e??"Transaksi gagal.");const l=m.toLowerCase();if(l.includes("user rejected")||l.includes("user denied"))return "Transaksi dibatalkan di wallet.";if(l.includes("insufficient funds"))return "Saldo ETH Base Sepolia tidak cukup untuk gas.";if(l.includes("deadlineexpired"))return "Order sudah melewati batas waktu pembayaran.";if(l.includes("invalidorderstate"))return "Order tidak berada pada status yang dapat dilanjutkan.";if(l.includes("insufficient allowance"))return "Allowance payment token ke Escrow belum mencukupi.";return m.length>260?`${m.slice(0,260)}…`:m}

async function logsChunked(client:PublicClient,from:bigint,to:bigint){const out:Awaited<ReturnType<PublicClient["getLogs"]>>=[];for(let c=from;c<=to;){const e=c+MAX_LOG_RANGE-1n<to?c+MAX_LOG_RANGE-1n:to;out.push(...await timeout(client.getLogs({address:USTETU_ESCROW_ADDRESS,fromBlock:c,toBlock:e}),RPC_TIMEOUT*3,"RPC logs timeout"));c=e+1n}return out}

async function scanPending(client:PublicClient,listingId:bigint,buyer:`0x${string}`):Promise<ResumeOrder|null>{
  const latest=await timeout(client.getBlockNumber(),RPC_TIMEOUT,"RPC block timeout");
  const from=latest>SCAN_BLOCKS?latest-SCAN_BLOCKS:0n;
  const logs=await logsChunked(client,from,latest); let found:ResumeOrder|null=null;
  for(const log of logs){try{const d=decodeEventLog({abi:escrowAbi,data:log.data,topics:log.topics,eventName:"OrderCreated"});if(d.eventName!=="OrderCreated")continue;const a=d.args;if(a.listingId!==listingId||a.buyer.toLowerCase()!==buyer.toLowerCase())continue;const o=await timeout(client.readContract({address:USTETU_ESCROW_ADDRESS,abi:escrowAbi,functionName:"getOrder",args:[a.orderId]}),RPC_TIMEOUT,"RPC order timeout");const state=Number(o.state);if((state===PAYMENT_PENDING||state===PAID)&&(!found||a.orderId>found.orderId))found={orderId:a.orderId,tokenAmount:a.tokenAmount,grossPayment:a.grossPayment,state,createHash:log.transactionHash??undefined}}catch{}}
  return found;
}

async function readKnownOrder1(client:PublicClient,listingId:bigint,buyer:`0x${string}`):Promise<ResumeOrder|null>{
  if(listingId!==2n)return null;
  try{const o=await timeout(client.readContract({address:USTETU_ESCROW_ADDRESS,abi:escrowAbi,functionName:"getOrder",args:[1n]}),RPC_TIMEOUT,"RPC Order #1 timeout");if(o.listingId!==listingId||o.buyer.toLowerCase()!==buyer.toLowerCase())return null;const state=Number(o.state);if(state!==PAYMENT_PENDING&&state!==PAID)return null;return {orderId:1n,tokenAmount:o.tokenAmount,grossPayment:o.grossPayment,state};}catch{return null}
}

async function waitReceipt(client:PublicClient,hash:`0x${string}`){for(let i=0;i<20;i++){try{const r=await timeout(client.getTransactionReceipt({hash}),RPC_TIMEOUT,"RPC receipt timeout");if(r.status!=="success")throw new Error("Transaksi on-chain gagal atau di-revert.");return r}catch(e){const m=e instanceof Error?e.message.toLowerCase():"";if(m.includes("revert")||m.includes("on-chain gagal"))throw e;await sleep(700)}}throw new Error(`Receipt belum terbaca. Transaksi tidak dikirim ulang. Tx: ${hash}`)}

export default function BuyModal(p:Props){
  const {open,onClose,onCompleted,listingId,symbol,price,available,minOrderAmount,maxOrderAmount,paymentToken,tokenDecimals,paymentDecimals,paymentSymbol}=p;
  const {address,isConnected}=useAccount(); const chainId=useChainId(); const {switchChainAsync}=useSwitchChain(); const client=usePublicClient(); const {writeContractAsync}=useWriteContract();
  const [amount,setAmount]=useState("1"); const [step,setStep]=useState<Step>("idle"); const [status,setStatus]=useState(""); const [err,setErr]=useState(""); const [orderId,setOrderId]=useState<bigint|null>(null); const [tx,setTx]=useState<TxHashes>({}); const [resume,setResume]=useState<ResumeOrder|null>(null); const [checking,setChecking]=useState(false);
  const {data:balance,refetch:refetchBalance}=useReadContract({address:paymentToken,abi:erc20PaymentAbi,functionName:"balanceOf",args:address?[address]:undefined,query:{enabled:Boolean(address)}});
  const min=formatUnits(minOrderAmount,tokenDecimals), max=formatUnits(maxOrderAmount,tokenDecimals), avail=formatUnits(available,tokenDecimals);
  const parsed=useMemo(()=>{try{return amount&&Number(amount)>0?parseUnits(amount,tokenDecimals):null}catch{return null}},[amount,tokenDecimals]);
  const preview=useMemo(()=>!parsed?0n:(parsed*price)/10n**BigInt(tokenDecimals),[parsed,price,tokenDecimals]);
  const display=resume?.grossPayment??preview; const busy=["creating","approving","funding","completing"].includes(step); const storageKey=key(chainId,address,listingId);

  const readOrder=async(id:bigint)=>{if(!client)return null;const o=await timeout(client.readContract({address:USTETU_ESCROW_ADDRESS,abi:escrowAbi,functionName:"getOrder",args:[id]}),RPC_TIMEOUT,"RPC order state timeout");return o};
  const readAllowance=async()=>address&&client?timeout(client.readContract({address:paymentToken,abi:erc20PaymentAbi,functionName:"allowance",args:[address,USTETU_ESCROW_ADDRESS]}),RPC_TIMEOUT,"RPC allowance timeout"):0n;
  const readBalance=async()=>address&&client?timeout(client.readContract({address:paymentToken,abi:erc20PaymentAbi,functionName:"balanceOf",args:[address]}),RPC_TIMEOUT,"RPC balance timeout"):0n;
  const waitState=async(id:bigint,wanted:number[])=>{for(let i=0;i<20;i++){try{const o=await readOrder(id);if(o){const s=Number(o.state);if(wanted.includes(s))return s}}catch{}await sleep(1000)}return null};

  useEffect(()=>{let cancelled=false;async function detect(){if(!open||!client||!address)return;setChecking(true);setResume(null);try{if(chainId!==baseSepolia.id){setStatus("Hubungkan wallet ke Base Sepolia untuk memulihkan Order #1.");return}const stored=load(storageKey);let found:ResumeOrder|null=null;if(stored&&stored.escrow?.toLowerCase()===USTETU_ESCROW_ADDRESS.toLowerCase()&&stored.buyer?.toLowerCase()===address.toLowerCase()&&stored.listingId===listingId.toString()){try{const o=await readOrder(BigInt(stored.orderId));const s=Number(o.state);if(s===PAYMENT_PENDING||s===PAID)found={orderId:BigInt(stored.orderId),tokenAmount:BigInt(stored.tokenAmount),grossPayment:BigInt(stored.grossPayment),state:s,createHash:stored.createHash}}catch{}}
      if(!found)found=await readKnownOrder1(client,listingId,address);
      if(!found)found=await scanPending(client,listingId,address);
      if(found&&!cancelled){setResume(found);setOrderId(found.orderId);setAmount(formatUnits(found.tokenAmount,tokenDecimals));setStatus("");save(storageKey,{chainId,escrow:USTETU_ESCROW_ADDRESS,listingId:listingId.toString(),buyer:address,orderId:found.orderId.toString(),tokenAmount:found.tokenAmount.toString(),grossPayment:found.grossPayment.toString(),createHash:found.createHash})}
    }catch{}finally{if(!cancelled)setChecking(false)}}void detect();return()=>{cancelled=true}},[open,client,address,chainId,listingId,storageKey,tokenDecimals]);

  if(!open)return null;
  const markComplete=async(id:bigint)=>{clear(storageKey);setResume(null);setStep("success");setStatus(`Order #${id} selesai. ${amount} ${symbol} berhasil dibeli.`);await refetchBalance();onCompleted()};
  const settle=async(id:bigint,gross:bigint,state:number,createHash?:`0x${string}`)=>{setOrderId(id);if(createHash)setTx(x=>({...x,create:createHash}));const tokenAmount=resume?.orderId===id?resume.tokenAmount:parsed;save(storageKey,{chainId,escrow:USTETU_ESCROW_ADDRESS,listingId:listingId.toString(),buyer:address!,orderId:id.toString(),tokenAmount:tokenAmount?.toString()??"0",grossPayment:gross.toString(),createHash});if(state===COMPLETED)return markComplete(id);
    if(state===PAYMENT_PENDING){if(await readBalance()<gross)throw new Error(`Saldo ${paymentSymbol} tidak cukup. Order #${id} membutuhkan ${formatUnits(gross,paymentDecimals)} ${paymentSymbol}.`);let allowance=await readAllowance();if(allowance<gross){setStep("approving");setStatus(`Konfirmasi approval ${formatUnits(gross,paymentDecimals)} ${paymentSymbol} di wallet…`);const h=await writeContractAsync({address:paymentToken,abi:erc20PaymentAbi,functionName:"approve",args:[USTETU_ESCROW_ADDRESS,gross]});setTx(x=>({...x,approve:h}));await waitReceipt(client!,h);allowance=await readAllowance()}if(allowance<gross)throw new Error(`Allowance ${paymentSymbol} belum mencukupi untuk Order #${id}.`);setStep("funding");setStatus(`Konfirmasi pembayaran ${formatUnits(gross,paymentDecimals)} ${paymentSymbol} di wallet…`);const h=await writeContractAsync({address:USTETU_ESCROW_ADDRESS,abi:escrowAbi,functionName:"fundOrder",args:[id]});setTx(x=>({...x,fund:h}));try{await waitReceipt(client!,h)}catch(e){const s=await waitState(id,[PAID,COMPLETED]);if(s!==PAID&&s!==COMPLETED)throw e}state=await waitState(id,[PAID,COMPLETED])??state}
    if(state===COMPLETED)return markComplete(id);if(state!==PAID)throw new Error(`Order #${id} belum PAID. Status on-chain: ${state}.`);setStep("completing");setStatus("Konfirmasi penyelesaian order di wallet…");const h=await writeContractAsync({address:USTETU_ESCROW_ADDRESS,abi:escrowAbi,functionName:"completeOrder",args:[id]});setTx(x=>({...x,complete:h}));try{await waitReceipt(client!,h)}catch(e){const s=await waitState(id,[COMPLETED]);if(s===COMPLETED)return markComplete(id);throw e}const final=await waitState(id,[COMPLETED]);if(final!==COMPLETED)throw new Error(`Order #${id} belum COMPLETED.`);await markComplete(id)};
  const resumeExisting=async()=>{if(!resume||!client||!address)return;setErr("");setStatus("");setTx({});try{setStatus(`Order #${resume.orderId} ditemukan. Nilai on-chain: ${formatUnits(resume.grossPayment,paymentDecimals)} ${paymentSymbol}.`);await settle(resume.orderId,resume.grossPayment,resume.state,resume.createHash)}catch(e){setStep("idle");setStatus("");setErr(errorText(e))}};
  const buy=async()=>{setErr("");setStatus("");setOrderId(null);setTx({});if(!isConnected||!address)return setErr("Hubungkan wallet terlebih dahulu.");if(chainId!==baseSepolia.id){try{setStatus("Mengganti jaringan ke Base Sepolia…");await switchChainAsync({chainId:baseSepolia.id});return setStatus("Jaringan sudah diarahkan ke Base Sepolia. Buka kembali Buy USTETU untuk memeriksa Order #1.")}catch(e){return setErr(errorText(e))}}if(!client)return setErr("RPC client belum siap.");if(resume)return resumeExisting();const recovered=await readKnownOrder1(client,listingId,address);if(recovered){setResume(recovered);setOrderId(recovered.orderId);setAmount(formatUnits(recovered.tokenAmount,tokenDecimals));return setStatus(`Order #${recovered.orderId} ditemukan. Tidak membuat order baru.`)}if(!parsed)return setErr(`Masukkan jumlah ${symbol} yang valid.`);if(parsed<minOrderAmount||parsed>maxOrderAmount||parsed>available)return setErr(`Jumlah harus ${min}–${max} ${symbol} dan tidak melebihi stok ${avail} ${symbol}.`);if((balance??0n)<preview)return setErr(`Saldo ${paymentSymbol} tidak cukup.`);try{setStep("creating");setStatus("Menunggu konfirmasi createOrder di wallet…");const h=await writeContractAsync({address:USTETU_ESCROW_ADDRESS,abi:escrowAbi,functionName:"createOrder",args:[listingId,parsed]});setTx(x=>({...x,create:h}));const r=await waitReceipt(client,h);let id=0n,gross=preview;for(const log of r.logs){try{const d=decodeEventLog({abi:escrowAbi,data:log.data,topics:log.topics,eventName:"OrderCreated"});if(d.eventName==="OrderCreated"){id=d.args.orderId;gross=d.args.grossPayment;break}}catch{}}if(id===0n)throw new Error("OrderCreated event tidak ditemukan.");await settle(id,gross,PAYMENT_PENDING,h)}catch(e){setStep("idle");setStatus("");setErr(errorText(e))}};
  const hashes=Object.entries(tx).filter(([,v])=>v);
  return <><button className="drawer-backdrop" aria-label="Close buy dialog" onClick={()=>{if(!busy)onClose()}}/><section className="buy-modal" role="dialog" aria-modal="true" aria-label={`Buy ${symbol}`}><div className="buy-modal-header"><div><span className="eyebrow">BUY TOKEN</span><h2>Buy {symbol}</h2></div><button className="drawer-close" type="button" onClick={()=>{if(!busy)onClose()}} disabled={busy}>×</button></div><div className="buy-summary"><div><span>Price</span><strong>{resume?`${formatUnits(resume.grossPayment,paymentDecimals)} ${paymentSymbol} total`:`${formatUnits(price,paymentDecimals)} ${paymentSymbol} / ${symbol}`}</strong></div><div><span>Available</span><strong>{avail} {symbol}</strong></div><div><span>Min / Max</span><strong>{min} / {max} {symbol}</strong></div></div><label className="buy-input-label" htmlFor="buy-amount">Amount ({symbol})</label><div className="buy-input-wrap"><input id="buy-amount" type="number" min={min} max={max} step="any" value={amount} onChange={e=>setAmount(e.target.value)} disabled={busy||step==="success"||Boolean(resume)}/><span>{symbol}</span></div><div className="buy-total"><span>Total payment</span><strong>{formatUnits(display,paymentDecimals)} {paymentSymbol}</strong></div>{checking&&<div className="buy-status">Memeriksa Order #1 dan order yang belum selesai…</div>}{resume&&!busy&&step!=="success"&&<div className="buy-status">Order #{resume.orderId} masih {resume.state===PAYMENT_PENDING?"menunggu pembayaran":"sudah dibayar"}. Nilai on-chain: {formatUnits(resume.grossPayment,paymentDecimals)} {paymentSymbol}. Tidak membuat order baru.</div>}{status&&<div className="buy-status">{status}</div>}{err&&<div className="buy-error">{err}</div>}{orderId!==null&&<div className="buy-order">Order #{orderId}</div>}{hashes.length>0&&<div className="buy-tx-list">{hashes.map(([label,h])=><a key={label} href={`${BASESCAN_TX}${h}`} target="_blank" rel="noreferrer"><span>{label==="create"?"Order":label==="approve"?"Approve":label==="fund"?"Payment":"Complete"}</span><strong>{hashShort(h as `0x${string}`)} ↗</strong></a>)}</div>}{resume?<button className="buy-submit" type="button" onClick={resumeExisting} disabled={busy||checking||step==="success"}>{step==="success"?"Purchased":`Resume Order #${resume.orderId}`}</button>:<button className="buy-submit" type="button" onClick={buy} disabled={busy||checking||step==="success"}>{step==="success"?"Purchased":`Buy ${symbol}`}</button>}<p className="buy-note">Transaksi diproses langsung melalui smart contract USTETU Escrow di Base Sepolia.</p></section></>;
}
