export const languages = { en: "English", id: "Indonesian", zh: "Chinese", ja: "Japanese", ko: "Korean" } as const;
export type Language = keyof typeof languages;

const en: Record<string, string> = {
  tagline:"Own What’s Next.", marketplace:"Marketplace", language:"Language", network:"Base Sepolia", connect:"Connect Wallet", foundation:"USTETU Web3 Marketplace", marketplaceEyebrow:"USTETU MARKETPLACE", findNext:"Find what’s next.", verifiedListings:"Verified token listings on Base Sepolia.", searchPlaceholder:"Search contract, token name or symbol", loading:"Loading blockchain data…", listing:"verified listing", listings:"listings", live:"Live", token:"Token", seller:"Seller", available:"Available", price:"Price", networkLabel:"Network", view:"View", unableRead:"Unable to read Base Sepolia data.", readingListing:"Reading Listing #1 from Escrow…", noMatch:"No matching token found.", verifiedToken:"VERIFIED TOKEN", name:"Name", symbol:"Symbol", decimals:"Decimals", contractAddress:"Contract Address", status:"Status", approved:"APPROVED", copyAddress:"Copy Address", baseScan:"BaseScan ↗", buy:"Buy", systemInfo:"SYSTEM INFORMATION", systemInfoSubtitle:"Understand the transaction flow before you trade.", howToBuy:"HOW TO BUY", chooseToken:"Choose Token", enterAmount:"Enter Amount", createOrder:"Create Order", approveUsdc:"Approve USDC", payment:"Payment", complete:"Complete", tokenToWallet:"USTETU → Buyer Wallet", approvalNote:"Approve USDC is only required when the current allowance is insufficient.", escrowProtection:"ESCROW PROTECTION", paymentWindow:"Payment window: 15 minutes", paymentWindowDesc:"If payment is not completed, the order expires and locked tokens return to available inventory.", autoRelease:"Auto Release: 24 hours", autoReleaseDesc:"After payment is escrowed, the buyer has 24 hours to complete the order. If not, the escrow can be auto-released.", howToSell:"HOW TO SELL", deposit:"Deposit USTETU", createListing:"Create Listing", buyerOrder:"Buyer Order", locked:"Token Locked", receiveUsdc:"Receive USDC", sellerFlow:"Seller funds remain claimable after settlement.", beforeTrade:"BEFORE YOU TRADE", beforeTradeDesc:"A wallet may ask for several confirmations. Complete each required transaction and do not submit the same order again while the current transaction is pending.", transactionProgress:"Transaction Progress", buyToken:"Buy Token", amount:"Amount", totalPayment:"Total payment", purchased:"Purchased", txNote:"Transactions are processed directly through the USTETU Escrow smart contract on Base Sepolia.", connecting:"Connecting…", close:"Close", systemClose:"Close system information"
};

const id: Record<string,string> = { ...en, language:"Bahasa", connect:"Hubungkan Wallet", marketplace:"Marketplace", marketplaceEyebrow:"USTETU MARKETPLACE", findNext:"Temukan yang berikutnya.", verifiedListings:"Listing token terverifikasi di Base Sepolia.", searchPlaceholder:"Cari contract, nama token atau simbol", loading:"Memuat data blockchain…", listing:"listing terverifikasi", listings:"listing", live:"Live", token:"Token", seller:"Penjual", available:"Tersedia", price:"Harga", networkLabel:"Jaringan", view:"Lihat", unableRead:"Tidak dapat membaca data Base Sepolia.", readingListing:"Membaca Listing #1 dari Escrow…", noMatch:"Token tidak ditemukan.", verifiedToken:"TOKEN TERVERIFIKASI", name:"Nama", symbol:"Simbol", decimals:"Desimal", contractAddress:"Alamat Contract", status:"Status", approved:"DISETUJUI", copyAddress:"Salin Alamat", buy:"Beli", systemInfo:"INFORMASI SISTEM", systemInfoSubtitle:"Pahami alur transaksi sebelum melakukan transaksi.", howToBuy:"CARA MEMBELI", chooseToken:"Pilih Token", enterAmount:"Masukkan Jumlah", createOrder:"Buat Order", approveUsdc:"Approve USDC", payment:"Pembayaran", complete:"Selesai", tokenToWallet:"USTETU → Wallet Buyer", approvalNote:"Approve USDC hanya diperlukan jika allowance saat ini tidak mencukupi.", escrowProtection:"PERLINDUNGAN ESCROW", paymentWindow:"Batas pembayaran: 15 menit", paymentWindowDesc:"Jika pembayaran tidak dilakukan, order kedaluwarsa dan token yang terkunci kembali ke inventory tersedia.", autoRelease:"Auto Release: 24 jam", autoReleaseDesc:"Setelah pembayaran masuk escrow, buyer memiliki 24 jam untuk menyelesaikan order. Jika tidak, escrow dapat melakukan auto-release.", howToSell:"CARA MENJUAL", deposit:"Deposit USTETU", createListing:"Buat Listing", buyerOrder:"Order Buyer", locked:"Token Terkunci", receiveUsdc:"Terima USDC", sellerFlow:"Dana seller menjadi claimable setelah settlement.", beforeTrade:"SEBELUM BERTRANSAKSI", beforeTradeDesc:"Wallet dapat meminta beberapa konfirmasi. Selesaikan setiap transaksi yang diperlukan dan jangan mengirim order yang sama lagi saat transaksi sebelumnya masih pending.", transactionProgress:"Progress Transaksi", buyToken:"Beli Token", amount:"Jumlah", totalPayment:"Total pembayaran", purchased:"Sudah Dibeli", txNote:"Transaksi diproses langsung melalui smart contract USTETU Escrow di Base Sepolia.", close:"Tutup", systemClose:"Tutup informasi sistem" };

const zh: Record<string,string> = { ...en, language:"语言", connect:"连接钱包", marketplace:"市场", marketplaceEyebrow:"USTETU 市场", findNext:"探索下一步。", verifiedListings:"Base Sepolia 上的已验证代币列表。", searchPlaceholder:"搜索合约、代币名称或符号", loading:"正在加载区块链数据…", listing:"个已验证列表", listings:"个列表", live:"实时", token:"代币", seller:"卖家", available:"可用", price:"价格", networkLabel:"网络", view:"查看", unableRead:"无法读取 Base Sepolia 数据。", readingListing:"正在从 Escrow 读取列表 #1…", noMatch:"未找到匹配代币。", verifiedToken:"已验证代币", name:"名称", symbol:"符号", decimals:"小数位", contractAddress:"合约地址", status:"状态", approved:"已批准", copyAddress:"复制地址", buy:"购买", systemInfo:"系统信息", systemInfoSubtitle:"交易前先了解完整交易流程。", howToBuy:"如何购买", chooseToken:"选择代币", enterAmount:"输入数量", createOrder:"创建订单", approveUsdc:"授权 USDC", payment:"支付", complete:"完成", tokenToWallet:"USTETU → 买家钱包", approvalNote:"仅当当前授权额度不足时才需要授权 USDC。", escrowProtection:"托管保护", paymentWindow:"支付窗口：15 分钟", paymentWindowDesc:"如果未完成支付，订单将过期，被锁定的代币会回到可用库存。", autoRelease:"自动释放：24 小时", autoReleaseDesc:"支付进入托管后，买家有 24 小时完成订单，否则托管可自动释放。", howToSell:"如何出售", deposit:"存入 USTETU", createListing:"创建列表", buyerOrder:"买家订单", locked:"代币锁定", receiveUsdc:"获得 USDC", sellerFlow:"结算后卖家的资金可领取。", beforeTrade:"交易前须知", beforeTradeDesc:"钱包可能要求多次确认。完成每笔必要交易，在当前交易等待期间不要重复提交相同订单。", transactionProgress:"交易进度", amount:"数量", totalPayment:"支付总额", purchased:"已购买", txNote:"交易通过 Base Sepolia 上的 USTETU Escrow 智能合约直接处理。", close:"关闭", systemClose:"关闭系统信息" };

const ja: Record<string,string> = { ...en, language:"言語", connect:"ウォレット接続", marketplace:"マーケットプレイス", marketplaceEyebrow:"USTETU マーケットプレイス", findNext:"次を見つけよう。", verifiedListings:"Base Sepolia の検証済みトークン一覧。", searchPlaceholder:"コントラクト、トークン名、シンボルを検索", loading:"ブロックチェーンデータを読み込み中…", listing:"件の検証済みリスティング", listings:"件のリスティング", live:"ライブ", token:"トークン", seller:"販売者", available:"利用可能", price:"価格", networkLabel:"ネットワーク", view:"表示", unableRead:"Base Sepolia のデータを読み取れません。", readingListing:"Escrow から Listing #1 を読み込み中…", noMatch:"一致するトークンがありません。", verifiedToken:"検証済みトークン", name:"名前", symbol:"シンボル", decimals:"小数桁", contractAddress:"コントラクトアドレス", status:"ステータス", approved:"承認済み", copyAddress:"アドレスをコピー", buy:"購入", systemInfo:"システム情報", systemInfoSubtitle:"取引前に取引フローを確認してください。", howToBuy:"購入方法", chooseToken:"トークンを選択", enterAmount:"数量を入力", createOrder:"注文を作成", approveUsdc:"USDCを承認", payment:"支払い", complete:"完了", tokenToWallet:"USTETU → 購入者ウォレット", approvalNote:"現在のallowanceが不足している場合のみUSDC承認が必要です。", escrowProtection:"エスクロー保護", paymentWindow:"支払期限：15分", paymentWindowDesc:"支払いが完了しない場合、注文は期限切れとなり、ロックされたトークンは利用可能在庫に戻ります。", autoRelease:"自動リリース：24時間", autoReleaseDesc:"支払いがエスクローに入った後、購入者は24時間以内に注文を完了できます。完了しない場合は自動リリースできます。", howToSell:"販売方法", deposit:"USTETUを入金", createListing:"リスティング作成", buyerOrder:"購入者注文", locked:"トークンをロック", receiveUsdc:"USDCを受取", sellerFlow:"決済後、販売者の資金は請求可能になります。", beforeTrade:"取引前の注意", beforeTradeDesc:"ウォレットで複数回の確認が求められる場合があります。必要な各取引を完了し、保留中に同じ注文を再送しないでください。", transactionProgress:"取引進捗", amount:"数量", totalPayment:"支払総額", purchased:"購入済み", txNote:"取引はBase Sepolia上のUSTETU Escrowスマートコントラクトで直接処理されます。", close:"閉じる", systemClose:"システム情報を閉じる" };

const ko: Record<string,string> = { ...en, language:"언어", connect:"지갑 연결", marketplace:"마켓플레이스", marketplaceEyebrow:"USTETU 마켓플레이스", findNext:"다음 기회를 찾아보세요.", verifiedListings:"Base Sepolia의 검증된 토큰 목록입니다.", searchPlaceholder:"컨트랙트, 토큰 이름 또는 심볼 검색", loading:"블록체인 데이터를 불러오는 중…", listing:"개의 검증된 목록", listings:"개의 목록", live:"실시간", token:"토큰", seller:"판매자", available:"사용 가능", price:"가격", networkLabel:"네트워크", view:"보기", unableRead:"Base Sepolia 데이터를 읽을 수 없습니다.", readingListing:"Escrow에서 Listing #1을 읽는 중…", noMatch:"일치하는 토큰이 없습니다.", verifiedToken:"검증된 토큰", name:"이름", symbol:"심볼", decimals:"소수점", contractAddress:"컨트랙트 주소", status:"상태", approved:"승인됨", copyAddress:"주소 복사", buy:"구매", systemInfo:"시스템 정보", systemInfoSubtitle:"거래 전에 거래 흐름을 확인하세요.", howToBuy:"구매 방법", chooseToken:"토큰 선택", enterAmount:"수량 입력", createOrder:"주문 생성", approveUsdc:"USDC 승인", payment:"결제", complete:"완료", tokenToWallet:"USTETU → 구매자 지갑", approvalNote:"현재 allowance가 부족한 경우에만 USDC 승인이 필요합니다.", escrowProtection:"에스크로 보호", paymentWindow:"결제 시간: 15분", paymentWindowDesc:"결제가 완료되지 않으면 주문이 만료되고 잠긴 토큰은 사용 가능한 재고로 돌아갑니다.", autoRelease:"자동 릴리스: 24시간", autoReleaseDesc:"결제가 에스크로에 들어간 후 구매자는 24시간 내 주문을 완료할 수 있습니다. 완료하지 않으면 자동 릴리스가 가능합니다.", howToSell:"판매 방법", deposit:"USTETU 입금", createListing:"목록 생성", buyerOrder:"구매자 주문", locked:"토큰 잠금", receiveUsdc:"USDC 받기", sellerFlow:"정산 후 판매자의 자금은 출금할 수 있습니다.", beforeTrade:"거래 전 안내", beforeTradeDesc:"지갑에서 여러 번 확인을 요청할 수 있습니다. 필요한 각 거래를 완료하고 현재 거래가 대기 중일 때 같은 주문을 다시 제출하지 마세요.", transactionProgress:"거래 진행", amount:"수량", totalPayment:"총 결제액", purchased:"구매 완료", txNote:"거래는 Base Sepolia의 USTETU Escrow 스마트 컨트랙트를 통해 직접 처리됩니다.", close:"닫기", systemClose:"시스템 정보 닫기" };

export const translations: Record<Language, Record<string,string>> = { en, id, zh, ja, ko };
export const getInitialLanguage = (): Language => {
  if (typeof window === "undefined") return "en";
  const saved = window.localStorage.getItem("ustetu-language") as Language | null;
  return saved && saved in languages ? saved : "en";
};
